name: stress-ng
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  release:
    types: [published, created, edited, deleted, prereleased, released]
  workflow_dispatch:

jobs:
  stress-test:
    runs-on: puzl-cloud
    steps:
    - name: Run
      run: |
        df -h
        mount
        tree -a /.puzl
