name: stress-ng
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  stress-test:
    runs-on: puzl-cloud
    steps:
    - name: Install stress-ng
      run: |
        # Update package list and install stress-ng
        sudo apt-get update
        sudo apt-get install -y stress-ng

    - name: Run cyclic CPU stress test
      run: |
        # Run 3 cycles of stress (1m) + cooldown (1m)
        for i in {1..3}; do
          echo "Cycle $i/3: Stress testing 3 CPU cores for 1 minute..."
          stress-ng --cpu 3 --timeout 1m
          
          echo "Pausing for 1 minute..."
          sleep 60
        done

