name: stress-ng
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  stress-test:
    runs-on: puzl-cloud
    steps:
    - name: Run
      run: |
        sleep 5
        df -h
        mount
        sleep 1800
